# Generated by Django 4.0.4 on 2022-05-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmatchaut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
