# Generated by Django 4.0.4 on 2022-05-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmatchaut', '0002_abstractuser_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractuser',
            name='teste1',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
