# Generated by Django 4.0.4 on 2022-05-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petmatchaut', '0003_abstractuser_teste1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractuser',
            name='teste1',
        ),
    ]
