# Generated by Django 4.0.4 on 2022-05-05 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petmatchaut', '0004_remove_abstractuser_teste1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='abstractuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='abstractuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='abstractuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='abstractuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='abstractuser',
            name='username',
        ),
        migrations.AddField(
            model_name='abstractuser',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
