# Generated by Django 4.0.4 on 2022-05-06 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petmatchaut', '0007_pet_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet_perfil',
            name='user',
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
