# Generated by Django 4.0.4 on 2022-05-06 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petmatchaut', '0008_remove_pet_perfil_user_alter_profileinfo_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet_perfil',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
