# Generated by Django 4.0.4 on 2022-05-06 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petmatchaut', '0009_pet_perfil_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet_perfil',
            name='user',
        ),
        migrations.AddField(
            model_name='pet_perfil',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pet_perfil',
            name='pet_image',
            field=models.ImageField(default='default.jpg', upload_to='pet_pics'),
        ),
        migrations.AlterField(
            model_name='pet_perfil',
            name='pet_name',
            field=models.CharField(default='your pet name', max_length=30),
        ),
        migrations.DeleteModel(
            name='ProfileInfo',
        ),
    ]
