# Generated by Django 4.0.4 on 2022-05-06 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('petmatchaut', '0010_remove_pet_perfil_user_pet_perfil_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_perfil',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
