# Generated by Django 4.0.4 on 2022-05-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmatchaut', '0012_rename_owner_pet_perfil_pet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet_perfil',
            name='pet_image',
            field=models.ImageField(default='default.jpg', upload_to='pet_pics/'),
        ),
        migrations.AlterField(
            model_name='pet_perfil',
            name='pet_name',
            field=models.CharField(max_length=30),
        ),
    ]
